### ISSUE TITLE
Participants can't input measurements

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#100]
Participants should be given access to input measurements on the systems they're participating in (however; subscribers should not be able to do this).

**Comment by jessicaday** [comment]
Assigning Denise - If someone is designated as a participant in a system ,they should be able to contribute data to that system. The idea is that a teacher could be the administrator for a system (complete control) but that their students could each be participants in that system (with their own profile page) and could collect/contribute data. This was supposed to be built in originally, but currently this function doesn't work.

**Comment by weiju** [comment]
Discovered the problem why this does not work: This function is conceptually implemented in the wrong way. The first thing is that the menu for the system social page only works for system administrators.
The problem propagates to these pages:

1. System Analysis
2. System log changes
3. System measurements

The templates for these pages contain a serious flaw: Conditional rendering based on checking the user who created the system. Not only does this check for the wrong condition, but it also checks in the wrong layer. This needs to be at least checked in the views.py layer and then the check should redirect to a separate page, handling this in rendering feels unnecessarily complicated and cluttered.

**Comment by weiju** [comment]
done. This required the fundamental changes that I mentioned above on

- System analysis page
- System social page
- Log Changes/Annotation page
- Measurements page
- System overview page
as well as the analysis and global controller views
