### ISSUE TITLE
Calendar/time/date controller pops up when creating a system date/time

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#102]
When creating a system or inputting data

**Comment by weiju** [comment]
not sure if I understand that correctly, it does pop up or it does not ? Also, which browser and operating system ?

**Comment by jessicaday** [comment]
As in it SHOULD pop up but it doesn't. This refers to the email you sent
earlier about this being a harder thing to change than we originally
thought, I believe.

*Jessica Day, M.S.*
Project Coordinator, Educator
Baliga Lab <https://www.systemsbiology.org/people/faculty/baliga-lab/>
and Systems
Education Experiences <http://baliga.systemsbiology.net/drupal/education/>

*Institute for Systems Biology*
401 Terry Ave. North, Seattle, WA 98109
p 206.732.1290 | f 206.732.1299
https://www.systemsbiology.org/
http://baliga.systemsbiology.net/drupal/education/
http://www.facebook.com/systemseducation
https://twitter.com/SystemsEd/

Check out the latest ISB news at http://www.systemsbiology.org/news/!

**Comment by weiju** [comment]
I believe this problem should not occur anymore, I put in some fixes, so it should work on current non-Chrome browsers that are not named Internet Explorer, could you please try if this is the case.
