### ISSUE TITLE
Add ability to include system profile picture

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#105]
On system page

**Comment by jessicaday** [comment]
Attaching Denise as assignee - this should be a relatively quick issue to resolve. We need the ability for each system to have it's own profile picture (requiring the option to browse from files on your computer and download).

**Comment by weiju** [comment]
see issues #108 and #109, we need to redesign the system data forms

**Comment by weiju** [comment]
I've ported the function to upload the profile picture from the prototype system
