### ISSUE TITLE
Edit system characteristics

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#108]
Users should be able to edit the number/type of plants and fish in their system if they accidentally input the wrong information. However, a warning should pop up that states "Only edit plant and fish information if it was incorrectly entered the first time. If you are simply changing the number/type of fish or plant in your system, use the "annotations" section in the data input tab to harvest plants, add plants, and remove fish or add fish." Once the user updates information in the "annotations section, this should automatically update their system characteristics so it doesn't still say the original number/type of plants/fish they began with.

**Comment by jessicaday** [comment]
This is priority #2

**Comment by weiju** [comment]
It looks like there is currently no way to edit system data, which should be an opportunity to revise our input forms and add multiple fish/plant and system images (issue #105 )

**Comment by weiju** [comment]
First step: added ability to change the system's name. This is mainly to establish the functional flow and
to ensure that everything will be working

**Comment by jessicaday** [comment]
Perfect. Thanks for getting started on this Wei-ju! So glad this function
will be available to our users soon :)


*Jessica Day, M.S.*
Project Manager
Baliga Lab <https://www.systemsbiology.org/people/faculty/baliga-lab/>
and Systems
Education Experiences <http://baliga.systemsbiology.net/drupal/education/>

*Institute for Systems Biology*
401 Terry Ave. North, Seattle, WA 98109
p 206.732.1290 | f 206.732.1299
https://www.systemsbiology.org/
http://baliga.systemsbiology.net/drupal/education/
http://www.facebook.com/systemseducation
https://twitter.com/SystemsEd/

Check out the latest ISB news at http://www.systemsbiology.org/news/!

**Comment by weiju** [comment]
added the option to edit plant and fish types so it should be a bit more useful now

**Comment by weiju** [comment]
added the notice, a security check if the user is able to administrate the system and another link to edit in the overview view. I am unsure about the annotations section, because it seems it is incomplete ? You can not specify the fish/plant type to remove or the number
