### ISSUE TITLE
Weather - weather information when blocked the location

### ISSUE THREAD

**Issue by yogimiraje** [baliga-lab/pf1010-web#72]
There is no warning message if I block my location on Weather widget. I just see the heading weather, which should be either hidden or a message should be there or may be link to turn the location on ?

![screen shot 2016-04-24 at 11 38 39 am](https://cloud.githubusercontent.com/assets/8564999/14768498/0eea62fa-0a12-11e6-92dc-b3cd5d162659.JPG)

**Comment by weiju** [comment]
the entire user interface is changing, so this will be fixed in a different way while changes happen
