### ISSUE TITLE
UI- Timestamp insert - Inconsistency in timezones

### ISSUE THREAD

**Issue by yogimiraje** [baliga-lab/pf1010-web#75]
I added a couple of nitrate measurements for today 10 am (EST) . The time I see in database / graph 2 pm. So looks like we are inserting timestamps in GMT. 
When I inserted the annotation , the timestamp is EST.
As DAV team compares the annotation timestamp with measurement timestamp to find the closest measurement point for an annotation , this may lead to confusion. 
Is it possible to keep the dates in consistent timezone format ?
Also not sure about having GMT format to be displayed to user. This is different issue altogether, but at least we can mention about timezone , otherwise user will be confused looking at the timestamps.

**Comment by weiju** [comment]
I changed the measurement time to be sent in UTC.
