### ISSUE TITLE
Fix "date created" issue

### ISSUE THREAD

**Issue by jessicaday** [baliga-lab/pf1010-web#95]
Currently, must choose today's date or later to create a system. This should be changed so users can select a date before today's date. Wei-ju will work on this. @weiju

**Comment by weiju** [comment]
i don't see anything that would prevent the system from creating any early dates, what I see though is that the date parsing is not working in many cases.

**Comment by jessicaday** [comment]
That may be what the students meant. If you're able to fix it, that would be great!
